//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualInventory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string StoreItemName { get; set; }
        public Nullable<int> StoreItemId { get; set; }
        public Nullable<decimal> ItemCount { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public Nullable<int> IndividualId { get; set; }
    
        public virtual Individual Individual { get; set; }
        public virtual StoreInventory StoreInventory { get; set; }
    }
}
