//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDisposal
    {
        public int Id { get; set; }
        public Nullable<int> StoreItemId { get; set; }
        public Nullable<decimal> ItmeCount { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Disposaldate { get; set; }
    }
}
