//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreInventory()
        {
            this.ZoneInventories = new HashSet<ZoneInventory>();
            this.IndividualInventories = new HashSet<IndividualInventory>();
        }
    
        public int Id { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> ItemCount { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<decimal> AvailableQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZoneInventory> ZoneInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualInventory> IndividualInventories { get; set; }
    }
}
