//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePurchaseItem
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> StoreItemId { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> ItemCount { get; set; }
        public string InvoiceNumber { get; set; }
        public string VendorName { get; set; }
        public string PurchaseDescription { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Purchasedate { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
    }
}
