//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneInventory
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> StoreItemId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<decimal> ItemCount { get; set; }
    
        public virtual StoreInventory StoreInventory { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
